---
- name: HELM | Download and extract binary
  unarchive:
    src: "{{helm_tar_url}}"
    dest: "/tmp"
    remote_src: yes

- name: HELM | Move binary to /usr/bin/helm
  copy:
    src: "/tmp/linux-amd64/helm"
    dest: "/usr/bin/helm"
    owner: "{{k8s_admin_user}}"
    group: "{{k8s_admin_group}}"
    mode: 755
    remote_src: yes

- name: HELM | Cleanup downloads
  file:
    path: /tmp/linux-amd64
    state: absent

- name: HELM | Add stable repo
  become: false
  command: helm repo add stable https://charts.helm.sh/stable
